[package]
name = "fingerprint_gui"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
gtk4 = { version = "0.6", features = ["v4_6"] }
once_cell = "1.21.3"

[build-dependencies]
glib-build-tools = "0.21"
